### ISSUE TITLE
[Feature Request] - Expand the sample to include Challenge handling and user authentication realms

### ISSUE THREAD

**Issue by hitchan** [MobileFirst-Platform-Developer-Center/StarterApplicationAndroid#1]
Would it be possible to expand this sample? It seems overly simple. For example, Challenge handlers and handling of multiple realms.

**Comment by IdanAdar** [comment]
You can review the security samples for challenge handlers implementation; there is no value in extending this sample to do the same (and it is also not the purpose of this sample to do so).
